### ISSUE TITLE
missing files of zero coverage in html output

### ISSUE THREAD

**Issue by kcwu** [mrash/afl-cov#11]
afl-cov line 438 combined "base" and "info" into "final". So "final" contains data about zero coverage. However, the next step, afl-cov line 444, generate "final" again using "info" as input. Therefore, if there are some files with zero coverage, that file will be missing in the final html output.

**Comment by mrash** [comment]
Thanks, I'll get this fixed.

**Comment by mrash** [comment]
Even though I believe this bug is fixed in 1e6cf0d, if you have a chance to test it please let me know if there are any issues.

**Comment by kcwu** [comment]
I guess I won't try it in near future.

**Comment by mrash** [comment]
Understood, thanks for letting me know. Most importantly, thanks for reporting the original bug. afl-cov 0.4 will be released soon.
