### ISSUE TITLE
use subprocess32 instead of subprocess

### ISSUE THREAD

**Issue by danstender** [mrash/afl-cov#13]
Hi Michael,

for the Debian package, we've patched afl-cov to import subprocess32 [1] instead of Python 2 stdlib subprocess, which is highly recommended to replace on POSIX systems. Do you would like to apply that upstream?

[1] https://pypi.python.org/pypi/subprocess32/

**Comment by mrash** [comment]
I'd like to take a look at this. Can you point me to a patch?

**Comment by danstender** [comment]
The patch is:

--- a/afl-cov
+++ b/afl-cov
@@ -31,7 +31,7 @@
 from sys import argv
 import errno
 import re
-import subprocess
+import subprocess32
 import glob
 import string
 import argparse

I've seen that some apps are using import-if-available constructs like e.g. Ocrodjvu:
https://sources.debian.net/src/ocrodjvu/0.9.1-1/lib/ipc.py/

**Comment by danstender** [comment]
We've got afl-cov in Debian now: https://tracker.debian.org/pkg/afl-cov (new package tracker, not yet fully polulated).

**Comment by mrash** [comment]
Excellent, thanks.
