### ISSUE TITLE
doesn't handle master/slave directories

### ISSUE THREAD

**Issue by newsham** [mrash/afl-cov#15]
If you're using "-M" and "-S" options to afl-fuzz, you get output directories "outputs/name1/" "outputs/name2/" etc. with queue directories under these.  This confuses afl-cov which expects "outputs/queue" to exist.

**Comment by mrash** [comment]
Thanks for reporting this. I'll get it fixed.

**Comment by mrash** [comment]
This has been fixed in git master in preparation for the 0.4 release. If you have time, would you mind testing it out?

**Comment by mrash** [comment]
Closing this issue for now - please reopen if there appears to be any bugs.

**Comment by newsham** [comment]
Sorry for the delay, been busy here.  Seems to be working.  One weird thing:

./afl-cov -d o --live --coverage-cmd ./ftls-gcov AFL_FILE --code-dir openssl-gcov/ssl/

Without --overwrite complains that o/cov exists, but it does not.  It works fine with --overwrite.

**Comment by mrash** [comment]
Thanks for reporting this, fixed.
