### ISSUE TITLE
--lcov-web-all crashes after the second report is finished

### ISSUE THREAD

**Issue by MarkusTeufelberger** [mrash/afl-cov#20]
Python complains that the file "lcov-web-final.html" already exists and kills the whole program, as soon as genhtml finishes the second report (around line 600).

http://stackoverflow.com/a/27103129 has a nice short function to fix this issue that works beautifully as a drop-in replacement.

**Comment by mrash** [comment]
Please let me know if you see any additional issues with this fix.
