### ISSUE TITLE
Missing index.html in final web output

### ISSUE THREAD

**Issue by patraulea** [mrash/afl-cov#26]
Afl-cov command was:

```bash
afl-cov -d .../fuzzout/ --coverage-cmd "./binary 1 AFL_FILE" --code-dir ~/project-gcov/
```
(started in ~/project-gcov/binary)

Note the missing index.html linked by lcov-web-final.html below:

```bash
fuzzout/cov/web$ ls -l
lcov-web-final.html -> /home/.../fuzzout//cov/web/f8/id:000373,sync:f2,src:000383/index.html

fuzzout/cov/web$ cd /home/.../fuzzout//cov/web/f8/id:000373,sync:f2,src:000383

cov/web/f8/id:000373,sync:f2,src:000383# ls
amber.png  emerald.png  gcov.css  glass.png  root  ruby.png  snow.png  updown.png
```

The only html file produced is a `mock-util.c.gcov.html` that only has coverage info for that mock-util.c file. Is this due to some failure to create the files or am I using some unsupported way of running afl-cov ?

**Comment by patraulea** [comment]
The cause was that the genhtml command failed. I ran it manually and it printed this:

```bash
genhtml: ERROR: cannot read /root/mock-util.c
```

I grepped for `SF:` lines through the `.lcov_info_final` input file passed to genhtml, and mock-util.c stood out as the only one with an incorrect path:

```bash
SF:/root/fuzz-gcov/mock/something.h
SF:/root/fuzz-gcov/file/fuzz-file.c
...
SF:/root/mock-util.c
```

mock-util.c's full path should be /root/fuzz-gcov/mock-util.c. It was probably not passed correctly since I passed --code-dir to afl-cov as /root/fuzz-gcov/file/ because that's where the resulting binary was, although some source files such ash mock-util.c were in fuzz-gcov/ . 

I ended up modifying the `.lcov_info_final` to fix mock-util.c's path and the genhtml command finished successfully. Would `--code-dir /root/fuzz-gcov` instead of `--code-dir /root/fuzz-gcov/file/` have avoided this ?

**Comment by mrash** [comment]
In general, --code-dir should be the same directory from which you compile
the project (or the path you set with 'make -C <dir>'). So, yes, I do think
setting --code-dir /root/fuzz-gcov would have worked, but please let me
know if that doesn't help. Are you running the latest afl-cov sources from
git master? I'm going to release 0.6 soon after a couple of additional
tweaks. I might need to add some stronger validation of --code-dir
specifics.

On Tue, May 24, 2016 at 6:52 AM, patraulea <notifications@github.com> wrote:

> The cause was that the genhtml command failed. I ran it manually and it
> printed this:
>
> genhtml: ERROR: cannot read /root/mock-util.c
>
> I grepped for SF: lines through the .lcov_info_final input file passed to
> genhtml, and mock-util.c stood out as the only one with an incorrect path:
>
> SF:/root/fuzz-gcov/mock/something.h
> SF:/root/fuzz-gcov/file/fuzz-file.c
> ...
> SF:/root/mock-util.c
>
> mock-util.c's full path should be /root/fuzz-gcov/mock-util.c. It was
> probably not passed correctly since I passed --code-dir to afl-cov as
> /root/fuzz-gcov/file/ because that's where the resulting binary was,
> although some source files such ash mock-util.c were in fuzz-gcov/ .
>
> I ended up modifying the .lcov_info_final to fix mock-util.c's path and
> the genhtml command finished successfully. Would --code-dir
> /root/fuzz-gcov instead of --code-dir /root/fuzz-gcov/file/ have avoided
> this ?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/afl-cov/issues/26#issuecomment-221234057>
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by patraulea** [comment]
Yup, I think --code-dir=the top of the src tree as opposed to the dir where the binary is solves it. Will comment/reopen if it doesn't. I was running the sources from git-master, yes. Thanks for the details.

**Comment by mrash** [comment]
Great, thanks for the confirmation.

On Thu, May 26, 2016 at 6:05 AM, patraulea <notifications@github.com> wrote:

> Yup, I think --code-dir=the top of the src tree as opposed to the dir
> where the binary is solves it. Will comment/reopen if it doesn't. I was
> running the sources from git-master, yes. Thanks for the details.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/mrash/afl-cov/issues/26#issuecomment-221830593>
>



-- 
Michael Rash | Founder
http://www.cipherdyne.org/
Key fingerprint = 53EA 13EA 472E 3771 894F  AC69 95D8 5D6B A742 839F

**Comment by dkasak** [comment]
I have a project with an erroneous reference to a file that doesn't exist which gets picked up by afl-cov. Even though reports for all other files get generated successfully, the final report doesn't get generated because `genhtml` dies on this nonexistent file. I then generated the final report manually using genhtml.

Perhaps passing `--ignore-errors source` to genhtml (which turns the error when a file doesn't exist into a warning) or an afl-cov option would be a good idea?
