### ISSUE TITLE
option to skip found_code_cov_binary test

### ISSUE THREAD

**Issue by umlaeute** [mrash/afl-cov#28]
i'm currently trying to use `afl-cov` to test a `dlopen()`ed library.

unfortunately the safety-nets in `afl-cov` give me a hard time, esp. the check whether the cmdline contains instrumented executables.

my main executable is *not* instrumented, but it loads a configuration that will trigger the `dlopen()`ing (and use) of an instrumented binary - so the coverage-cmd doesn't contain any hint about the binary in question.

rather than patching the `afl-cov` script, would it be possible to add a cmdline-flag to disable the `found_code_cov_binary`-test?

**Comment by mrash** [comment]
Thanks for the suggestion, added --disable-gcov-check
