### ISSUE TITLE
extend afl-cov to analyze the variable behaviors of applications?

### ISSUE THREAD

**Issue by zhunki** [mrash/afl-cov#33]
Hi there,
Firstly, thank you for your great work!
I’m thinking if you have any interest in extending your work to analyze the variable behaviors of fuzzing targets?
If we can identify which part of source code is responsible for indeterminancy and choose to not instrument that part, we can greatly improve the stability of fuzzing.
If you have any interest, I would like to help.
Cheers,

**Comment by mrash** [comment]
Hello, sorry for the late reply. This sounds like an interesting idea, though I'm not sure about the general implementation. Can you outline a plan of attack for this?
