### ISSUE TITLE
TypeError: logr() takes exactly 3 arguments (1 given)

### ISSUE THREAD

**Issue by NimdaKey** [mrash/afl-cov#38]
logr("[-] Coverage file '%s' does not exist, skipping." % lcov_file)

logr() takes exactly 3 arguments (1 given). 

# afl-cov
check  314 and 458 lines of the code

**Comment by mrash** [comment]
Fixed in f18e7a63, thanks. I've released afl-cov-0.6.2 as well that contains the fix.
